### ISSUE TITLE
Mixin apply fail log error?

### ISSUE THREAD

**Issue by Master65** [sf-inc/sihywtcamd#12]
```
[main/FATAL]: Mixin apply failed sihywtcamd.mixins.json:EndermanMixin -> net.minecraft.class_1560: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1560::addBlindnessE with priority 1000 cannot inject into net/minecraft/class_1560::method_7026(Lnet/minecraft/class_1657;)Z merged by safro.fabric.enchantments.mixin.enchantment.PumpkinHeadMixin with priority 1000 [PREINJECT Applicator Phase -> sihywtcamd.mixins.json:EndermanMixin -> Prepare Injections ->  -> handler$dno000$addBlindnessE(Lnet/minecraft/class_1657;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1560::addBlindnessE with priority 1000 cannot inject into net/minecraft/class_1560::method_7026(Lnet/minecraft/class_1657;)Z merged by safro.fabric.enchantments.mixin.enchantment.PumpkinHeadMixin with priority 1000 [PREINJECT Applicator Phase -> sihywtcamd.mixins.json:EndermanMixin -> Prepare Injections ->  -> handler$dno000$addBlindnessE(Lnet/minecraft/class_1657;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) [fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.minecraft.class_1299.<clinit>(class_1299.java:174) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:27) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:62) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_5464.<clinit>(class_5464.java:92) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_5458.method_30571(class_5458.java:46) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_5458$$Lambda$256/61653998.get(Unknown Source) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_5458$$Lambda$262/79685693.accept(Unknown Source) [intermediary-1.16.5.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) [?:1.8.0_51]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) [intermediary-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) [intermediary-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
```

This mod all of a sudden stopped working for some reason, returning error code 0 and returning this in the logs. There is no crash report or anything. 

Game Stats

Fabric 0.11.6
Sodium (Iris Shaders)
Minecraft 1.16.5
Running with optimization mods and no other mob mods except for elemental creepers, which does NOT change this outcome.
Running alongside sihywtcamc

**Comment by charlyb01** [comment]
Hi, thanks for the report! I guess you installed another mod recently that made my mod crash as I see something about PupkinHead that doesn't come from my mod `safro.fabric.enchantments.mixin.enchantment.PumpkinHeadMixin`. But anyway, I guess it should not cause an issue with 1.4.1 version and newer as I changed the enderman behavior and injection point. If the [new system](https://github.com/sf-inc/sihywtcamd/blob/master/CHANGELOG.md#enderman) is okay for you, I will update the very last version of the mod to 1.16.5 ;)

**Comment by Master65** [comment]
You know, come to think of it, I think I actually do have a custom enchant that is related to not triggering an enderman upon looking at it. I look forward to the newest version not conflicting with this. Thanks for letting me know.

**Comment by charlyb01** [comment]
So do you need a port to 1.16.5 of the newer version of the mod or are ou going to port your workd to 1.17.1?

**Comment by Master65** [comment]
Ahh, yeah sorry I never clarified. Yes, it would need to be made specifically for 1.16.5, since I cannot port my pack to 1.17 yet. I'd greatly appreciate a port for it!

**Comment by charlyb01** [comment]
Okay no problem, I'll do that for you today

**Comment by charlyb01** [comment]
It should be good now. Download the latest version on 1.16.5 and if it's working, close the issue

**Comment by Master65** [comment]
Thank you very much for taking the time to port it! This issue is no longer an issue, and as such, I'll close it.
